#!/usr/bin/env python3
"""
SP_209 — Shared sprint-frontmatter parser + active-claims reader.

Extracted from `validate_sprint_overlap.py` (SP_205) and `release-claims.py`
(SP_205) to satisfy Rule 18.7 ("defer specialization until you see three").
The pre-commit hook in `scripts/git-hooks/pre-commit.py` is the third
consumer; extraction now beats a third copy.

Public surface:
  - `parse_frontmatter(path)`     — parsed dict or {} when no frontmatter.
                                     Raises `FrontmatterParseError` on
                                     malformed YAML (caller decides
                                     refuse-vs-skip).
  - `read_active_claims(root, *,  — list of `Claim` objects for plans
       statuses=...)`                whose `status` is in `statuses`
                                     (default: {"In Progress"}).
  - `Claim`                       — dataclass: sprint_id, status, path,
                                     touches_paths, touches_checklist_items.
  - `OVERLAP_IGNORE_PATHS`        — Rule-7-mandated meta-docs excluded
                                     from path-prefix overlap checking
                                     (callers re-export as needed).

Git-backed claim-hygiene helpers (SP_956/SP_957 — lazily-called, NOT used at
import time, so pure-parser consumers like `validate_sprint_overlap` /
`release-claims` never shell git). Single source of truth (Rule 18.7) for the
commit-msg gate + the claim-hygiene diagnostic:
  - `STALE_DAYS`, `relative_to_days`, `plan_age_days`  — zombie-claim staleness.
  - `BROAD_FILE_THRESHOLD`, `tracked_files_under`,      — over-broad-claim
    `is_over_broad`                                       breadth. Both git
                                                          helpers fail-CLOSED
                                                          (error/timeout → safe
                                                          direction) with a
                                                          `timeout=5` ceiling.

YAML subset supported:
  - `key: value`
  - `key: [a, b, c]`              (inline list)
  - `key:` followed by indented `- item` lines  (block list)
  - Boolean coercion (`true`/`false` → bool)
  - Comments (`# ...`) and blank lines tolerated
  - Quoted-string trimming (single + double)

Not supported (raises `FrontmatterParseError`):
  - Unclosed `[` on inline list
  - Tab-indented block-list lines (must be space-indented; rejected
    explicitly to match docstring contract — Stage-5 HIGH-1 fix)
"""
from __future__ import annotations

import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

# SP_956 — a sprint plan whose file has had no commit in ≥ STALE_DAYS is a
# "zombie": its claims no longer block other agents (commit-msg foreign-claim
# skip) and it is surfaced by the claim-hygiene diagnostic. Single source of
# truth shared by `scripts/git-hooks/commit-msg.py` + `scripts/audit-claim-hygiene.py`.
STALE_DAYS = 14

# SP_957 — a claimed directory prefix whose subtree holds more than this many
# tracked files is "over-broad": the claiming sprint almost certainly does not
# co-edit them all, so a bare blanket claim foreign-blocks unrelated edits. The
# commit-msg foreign-claim skip relaxes such claims (relax-only) and the
# claim-hygiene diagnostic flags them. Single source of truth shared by
# `scripts/git-hooks/commit-msg.py` + `scripts/audit-claim-hygiene.py`
# (promoted from SP_955's audit script, Rule 18.7 — 2nd consumer). Tunable;
# deliberately conservative.
BROAD_FILE_THRESHOLD = 20

# Files every sprint touches by Rule 7 / Rule 16 — excluded from
# path-prefix overlap. Two sprints touching `PROGRESS.md` is the
# norm, not a coordination failure.
OVERLAP_IGNORE_PATHS: frozenset[str] = frozenset({
    "PROGRESS.md",
    "IMPLEMENTATION_CHECKLIST.md",
    "CLAUDE.md",
    "FEATURE_LIST.md",
    "PROJECT_ROADMAP.md",
    "USER_STORIES.md",
    "ARCHITECTURE.md",
    "DATA_SCHEMA.md",
    "CODEBASE_STRUCTURE.md",
    # SP_205 Stage-5 LOW-1: regenerated by validate_doc_freshness on every
    # green run; two parallel sprints both touching it is the norm.
    ".docs_reconciled",
})

_SPRINT_ID_RE = re.compile(r"^SP_(\d{3,})$")


class FrontmatterParseError(ValueError):
    """Raised when YAML frontmatter is malformed in a way that would
    silently corrupt downstream consumers (unclosed lists, etc.)."""

    def __init__(self, path: Path, line_no: int, reason: str) -> None:
        super().__init__(f"{path}:{line_no}: {reason}")
        self.path = path
        self.line_no = line_no
        self.reason = reason


@dataclass(frozen=True)
class Claim:
    """Active sprint claim distilled from a plan-file's frontmatter."""

    sprint_id: str
    status: str
    path: Path
    touches_paths: tuple[str, ...]
    touches_checklist_items: tuple[str, ...]


def parse_frontmatter(path: Path | str) -> dict[str, object]:
    """Parse YAML frontmatter from a file or text path.

    Returns {} when the file has no `---`-delimited frontmatter block.
    Raises `FrontmatterParseError` on malformed input.
    """
    p = Path(path)
    text = p.read_text(encoding="utf-8")
    return _parse_text(text, p)


def _parse_text(text: str, source: Path) -> dict[str, object]:
    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---\n", 4)
    if end == -1:
        return {}
    body = text[4:end]
    lines = body.splitlines()
    out: dict[str, object] = {}
    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or ":" not in stripped:
            i += 1
            continue
        key, _, raw = stripped.partition(":")
        key = key.strip()
        raw = raw.strip()
        if raw == "":
            # Block list: collect following indented `- item` lines.
            # Reject tab-indented (Stage-5 HIGH-1 — docstring contract).
            # Skip intra-block comment lines (Stage-5 MEDIUM-3 — silent
            # data-loss fix). Mixed inline + block on same key not
            # supported (block always wins when raw is empty).
            items: list[str] = []
            j = i + 1
            while j < len(lines):
                next_line = lines[j]
                if next_line == "":
                    j += 1
                    continue
                if next_line[0] == "\t":
                    raise FrontmatterParseError(
                        source, j + 1,
                        f"tab-indented block-list item under '{key}' "
                        f"— use space indentation"
                    )
                lstripped = next_line.lstrip(" ")
                if next_line == lstripped:
                    break  # not indented — block ends
                if lstripped.startswith("#"):
                    j += 1  # intra-block comment — skip, don't break
                    continue
                # Stage-5 iter-2 N-2 fix: an indented line that's not a
                # comment and doesn't start with `- ` is a typo (e.g.,
                # `  -src/foo` missing the space). Silently terminating
                # the block would void claims and disable collision
                # protection for this sprint — refuse instead.
                if not lstripped.startswith("- "):
                    if lstripped.startswith("-"):
                        raise FrontmatterParseError(
                            source, j + 1,
                            f"malformed block-list item under '{key}': "
                            f"missing space after `-` "
                            f"(got `{lstripped[:30]!r}`)"
                        )
                    break
                items.append(lstripped[2:].strip().strip('"').strip("'"))
                j += 1
            out[key] = items
            i = j
            continue
        if raw.startswith("["):
            if not raw.endswith("]"):
                raise FrontmatterParseError(
                    source, i + 1,
                    f"unclosed inline list for key '{key}'"
                )
            inner = raw[1:-1].strip()
            out[key] = [
                item.strip().strip('"').strip("'")
                for item in inner.split(",")
                if item.strip()
            ]
        elif raw.lower() in ("true", "false"):
            out[key] = raw.lower() == "true"
        else:
            out[key] = raw.strip('"').strip("'")
        i += 1
    return out


def read_active_claims(
    project_root: Path | str,
    *,
    statuses: Iterable[str] = ("In Progress",),
    on_parse_error: str = "raise",
) -> list[Claim]:
    """Walk `workspace/sprints/SP_*.md`, return `Claim` per plan whose
    `status` is in `statuses`.

    `on_parse_error` (Stage-5 HIGH-2 fix — pre-SP_209 callers had lenient
    parsers; this restores compatibility for callers that don't want a
    single malformed archived plan to crash the run):
      - "raise" (default) — `FrontmatterParseError` propagates. Used by
        the pre-commit hook which refuses on malformed frontmatter.
      - "skip" — malformed plan silently skipped (matches pre-refactor
        validate_sprint_overlap.py / release-claims.py behaviour).
      - "warn" — malformed plan skipped + diagnostic to stderr.
    """
    root = Path(project_root)
    sprints_dir = root / "workspace" / "sprints"
    out: list[Claim] = []
    if not sprints_dir.is_dir():
        return out
    if on_parse_error not in ("raise", "skip", "warn"):
        raise ValueError(
            f"on_parse_error must be 'raise'|'skip'|'warn', got {on_parse_error!r}"
        )
    status_set = set(statuses)
    for plan_path in sorted(sprints_dir.glob("SP_*.md")):
        try:
            fm = parse_frontmatter(plan_path)
        except OSError:
            continue
        except FrontmatterParseError as exc:
            if on_parse_error == "raise":
                raise
            if on_parse_error == "warn":
                print(
                    f"[_sprint_frontmatter] WARN: skipping malformed plan: {exc}",
                    file=sys.stderr,
                )
            continue
        status = fm.get("status")
        if status not in status_set:
            continue
        # Stage-5 M-1 fix: filename fallback uses first TWO underscore-segments
        # (`SP_010`) instead of just the first (`SP`).
        sprint_id = str(
            fm.get("sprint_id")
            or "_".join(plan_path.stem.split("_")[:2])
        )
        touches_paths = tuple(fm.get("touches_paths") or [])
        touches_checklist_items = tuple(fm.get("touches_checklist_items") or [])
        out.append(Claim(
            sprint_id=sprint_id,
            status=str(status),
            path=plan_path,
            touches_paths=touches_paths,
            touches_checklist_items=touches_checklist_items,
        ))
    return out


def is_sprint_id(s: str) -> bool:
    """True if `s` matches the canonical `SP_NNN` form (3+ digits)."""
    return bool(_SPRINT_ID_RE.match(s))


def relative_to_days(rel: str) -> int:
    """Parse a git `%cr` relative-date string into whole days.

    git `%cr` forms: "N seconds/minutes/hours/days/weeks/months/years ago".
    git uses "N hours ago" up to ~47h before switching to "N days ago", so the
    hour branch floor-divides (n // 24), else a ~1-day-old plan reports 0.
    Unparseable / unknown-unit input → 0 (conservative: treated as fresh, so a
    claim is never wrongly skipped). Promoted from SP_955's audit script
    (`scripts/audit-claim-hygiene.py`) as the single source of truth (Rule 18.7).

    NOTE: months/years use coarse 30/365-day arithmetic, but git `%cr` emits
    *days* around the 14-day staleness threshold (never "N months ago" for a
    ~2-week-old file), so the coarse months/years arithmetic only ever yields
    values far above the threshold (always stale) — it cannot misclassify near
    the boundary. Do not "fix" the 30/365 approximation; it is correct by where
    git's units switch over.
    """
    parts = rel.split()
    if len(parts) < 2:
        return 0
    try:
        n = int(parts[0])
    except ValueError:
        return 0  # non-numeric quantifier ("a"/"an"/word-form) — treat as fresh
    unit = parts[1]
    if unit.startswith("second") or unit.startswith("minute"):
        return 0
    if unit.startswith("hour"):
        return n // 24
    if unit.startswith("day"):
        return n
    if unit.startswith("week"):
        return n * 7
    if unit.startswith("month"):
        return n * 30
    if unit.startswith("year"):
        return n * 365
    return 0


def plan_age_days(root: Path, plan_path: Path) -> int | None:
    """Days since the last commit touching `plan_path`; None if untracked/git-error.

    cwd-independent: runs `git log` with `cwd=root` and normalises a relative
    `plan_path` against `root`. Fail-closed: git error / empty output → None (the
    caller treats None as NOT stale → no behaviour change). Promoted from SP_955.
    """
    target = plan_path if plan_path.is_absolute() else root / plan_path
    try:
        out = subprocess.run(
            ["git", "log", "-1", "--format=%cr", "--", str(target)],
            cwd=root, capture_output=True, text=True, check=False, timeout=5,
        ).stdout.strip()
    except (OSError, subprocess.TimeoutExpired):
        # Fail-closed: git missing / hung (e.g. .git lock contention from a
        # parallel agent on the per-commit hot path) → None → caller treats as
        # NOT stale → claim still blocks (no regression, never wedges the commit).
        return None
    if not out:
        return None
    return relative_to_days(out)


def tracked_files_under(root: Path, prefix: str) -> int:
    """Count git-tracked files under a directory-style claim prefix.

    Promoted from SP_955's `scripts/audit-claim-hygiene.py` as the single source
    of truth (Rule 18.7 — `scripts/git-hooks/commit-msg.py` is the 2nd consumer).

    LIMITATION (load-bearing for SP_957 relax-safety): glob-shaped claims
    (`dir/prefix*`) count as 0 because the trailing-slash pathspec
    `git ls-files -- <prefix>*/` treats the literal `*` as a path component and
    matches nothing. The CLAUDE.md `touches_paths` convention is plain directory
    prefixes, so over-broad globs are rare; a glob that slips through is counted
    0 → stays BELOW the over-broad threshold → still REFUSES (the safe
    direction — never wrongly relaxes a glob claim). Do NOT drop the trailing
    slash in the `git ls-files` argument: without it, `git ls-files -- <prefix>*`
    would expand and could cross the threshold, wrongly relaxing a glob claim.

    CONTRACT: `prefix` is a repo-RELATIVE `touches_paths` entry (the CLAUDE.md
    convention). An absolute / `../`-shaped prefix would make the `is_file()`
    probe and the `git ls-files` pathspec disagree, but both still resolve to 0
    → over-broad threshold not crossed → REFUSES (safe direction). Not validated
    here; the safe-direction fallback covers the malformed case.

    Fail-CLOSED on git error/timeout: returns 0 (→ below threshold → REFUSES),
    mirroring `plan_age_days`'s None→not-stale contract. The `timeout=5` ceiling
    matches `plan_age_days` so this per-commit hot-path helper cannot hang on
    `.git` index-lock contention from a parallel agent.
    """
    norm = prefix.rstrip("/")
    if not norm:
        return 0
    target = root / norm
    # Only directory prefixes can be over-broad; a leaf file claim is fine.
    if target.is_file():
        return 1
    try:
        out = subprocess.run(
            ["git", "ls-files", "--", f"{norm}/"],
            cwd=root, capture_output=True, text=True, check=False, timeout=5,
        ).stdout
    except (OSError, subprocess.TimeoutExpired):
        return 0
    return sum(1 for line in out.splitlines() if line.strip())


def is_over_broad(count: int) -> bool:
    """True iff a claim-prefix's tracked-file `count` exceeds BROAD_FILE_THRESHOLD.

    Single shared predicate so the commit-msg gate (`scripts/git-hooks/commit-msg.py`)
    and the claim-hygiene diagnostic (`scripts/audit-claim-hygiene.py`) encode the
    `>`-boundary identically — a future threshold/operator tweak (`>=` vs `>`)
    cannot desync the gate from the diagnostic. Exactly `BROAD_FILE_THRESHOLD`
    files = specific (refuses), per both consumers' original semantics.
    """
    return count > BROAD_FILE_THRESHOLD


if __name__ == "__main__":
    # Smoke: invoke as `python3 _sprint_frontmatter.py <project_root>`
    if len(sys.argv) < 2:
        print("usage: _sprint_frontmatter.py <project_root>", file=sys.stderr)
        sys.exit(2)
    claims = read_active_claims(sys.argv[1])
    for c in claims:
        print(f"{c.sprint_id} ({c.status}): paths={list(c.touches_paths)} items={list(c.touches_checklist_items)}")
    sys.exit(0)
